files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    translate_attributes: 0
    content_segmentation: 0
    languages_mapping:
      two_letters_code:
        ar-EG: ar-rEG
        zh-CN: zh-rCN
        zh-TW: zh-rTW
  - source: /app/src/debug/res/values/strings.xml
    translation: /app/src/debug/res/values-%two_letters_code%/strings.xml
    translate_attributes: 0
    content_segmentation: 0
    languages_mapping:
      two_letters_code:
        ar-EG: ar-rEG
        zh-CN: zh-rCN
        zh-TW: zh-rTW
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
