#!/bin/sh

gitTopLevel=$(git rev-parse --show-toplevel)

if python "$gitTopLevel/git_hooks/update_publish_tags.py" "$gitTopLevel"; then
   echo "adding '$gitTopLevel/.github/workflows/publish_release.yml' to git staging..."

   echo git add $gitTopLevel/.github/workflows/publish_release.yml

   echo git commit --amend --no-edit
fi;