name: Build App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 00 * * 5'

permissions: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.3

      - name: Build Debug APK
        run: bash gradlew app:assembleDebug

      - name: Generate Debug APK
        run: |
          apk=$(find app/build/outputs/apk/debug/*.apk)
          echo $apk
          echo ARTIFACT_NAME=$(basename $apk) >> $GITHUB_ENV
          echo ARTIFACT_PATH=$apk >> $GITHUB_ENV

      - name: Create Artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error
